project:
  type: website
  output-dir: docs

website:
  title: "Ruby Doeleman"
  site-url: "https://rubydoeleman.github.io"
  description: "PhD researcher in public economics and international corporate taxation at WU Vienna."

  navbar:
    background: white
    left:
      - text: "About"
        href: index.qmd
      - text: "Research"
        href: projects.qmd
      - text: "CV"
        href: cv.qmd

format:
  html:
    include-in-header:
      text: |
        <meta name="google-site-verification" content="XXXXX" />

        <script type="application/ld+json">
        {
          "@context": "https://schema.org",
          "@type": "Person",
          "name": "Ruby Doeleman",
          "url": "https://rubydoeleman.github.io/",
          "jobTitle": "PhD Student in Economics",
          "affiliation": {
            "@type": "Organization",
            "name": "WU Vienna University of Economics and Business"
          }
        }
        </script>

    theme:
      light: [cosmo]

    css: styles.css
    toc: false
    page-layout: full